# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

conv2df <- function(a, b) {
    .Call(`_gsignal_conv2df`, a, b)
}

conv2ds <- function(a, b) {
    .Call(`_gsignal_conv2ds`, a, b)
}

conv2dv <- function(a, b) {
    .Call(`_gsignal_conv2dv`, a, b)
}

